// Publishes the engine's primitive catalog and template workflows to the
// landing page (public/processly), so the site shows the real configs.
// Usage: npm run export:site
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CATEGORIES, PRIMITIVES } from '../src/catalog.js';
import { loadProject } from '../src/project.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const site = path.resolve(root, '../public/processly');
const banner = '// Generated by processly/scripts/export-site.ts — do not edit; change the engine and re-export.\n';

const primitives = {
  categories: CATEGORIES,
  primitives: PRIMITIVES.map(p => ({ id: p.id, cat: p.cat, label: p.label, desc: p.desc })),
};
fs.writeFileSync(path.join(site, 'primitives.js'), `${banner}window.PROCESSLY_PRIMITIVES = ${JSON.stringify(primitives, null, 2)};\n`);

const project = loadProject(path.join(root, 'templates'));
const workflows = Object.fromEntries([...project.workflows.entries()].sort(([a], [b]) => a.localeCompare(b)));
fs.writeFileSync(path.join(site, 'workflows.js'), `${banner}window.PROCESSLY_WORKFLOWS = ${JSON.stringify(workflows, null, 2)};\n`);

console.log(`exported ${primitives.primitives.length} primitives and ${project.workflows.size} workflows to ${path.relative(process.cwd(), site)}`);
